import * as React from "react";
import { getServerSession } from "next-auth";
import { authOptions } from "pages/api/auth/[...nextauth]";
import { Login, SessionProvider } from "components";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "cyrillic"],
  display: "auto",
});

export const metadata = {
  title: "ChatGPT",
  description: "Generated by create next app",
  applicationName: "ChatGPT",
  authors: {
    name: "Xasanov Javohir",
    url: "https://portfoliowebapp.vercel.app",
  },
  creator: "Xasanov Javohir",
  generator: "Next.js",
  keywords: [
    "nextjs",
    "chatgpt",
    "chatgpt uz",
    "openai",
    "openai uz",
    "ai",
    "xasanov javohir",
  ],
  openGraph: {
    description: "ChatGPT is online website to ask anything",
    emails: ["javokhirdev@mail.com", "xasanof17@gmail.com"],
    phoneNumbers: ["998900198505"],
    publishedTime: "01.03.,",
  },
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className={inter.className}>
      <body className="relative h-full min-h-screen bg-white dark:bg-black">
        <SessionProvider session={session}>
          {!session ? <Login /> : children}
        </SessionProvider>
      </body>
    </html>
  );
}
